-- People often copy jobs. When they do, the GM table does not exist anymore.
-- This line makes the job code work both inside and outside of gamemode files.
-- You should not copy this line into your code.
local GAMEMODE = GAMEMODE or GM
/*--------------------------------------------------------
Default teams. Please do not edit this file. Please use the darkrpmod addon instead.
--------------------------------------------------------*/
TEAM_CITIZEN = DarkRP.createJob("Citizen", {
	color = Color(124, 164, 231, 255),
	model = {
		"models/player/Group01/Female_01.mdl",
		"models/player/Group01/Female_02.mdl",
		"models/player/Group01/Female_03.mdl",
		"models/player/Group01/Female_04.mdl",
		"models/player/Group01/Female_06.mdl",
		"models/player/group01/male_01.mdl",
		"models/player/Group01/Male_02.mdl",
		"models/player/Group01/male_03.mdl",
		"models/player/Group01/Male_04.mdl",
		"models/player/Group01/Male_05.mdl",
		"models/player/Group01/Male_06.mdl",
		"models/player/Group01/Male_07.mdl",
		"models/player/Group01/Male_08.mdl",
		"models/player/Group01/Male_09.mdl"
	},
	description = [[The Citizen is the most basic level of society you can hold besides being a hobo. You have no specific role in city life.]],
	weapons = {},
	command = "citizen",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = false
})

TEAM_POLICE = DarkRP.createJob("Civil Protection", {
	color = Color(25, 25, 170, 255),
	model = {"models/player/police.mdl", "models/player/police_fem.mdl"},
	description = [[The protector of every citizen that lives in the city.
		You have the power to arrest criminals and protect innocents.
		Hit a player with your arrest baton to put them in jail.
		Bash a player with a stunstick and they may learn to obey the law.
		The Battering Ram can break down the door of a criminal, with a warrant for their arrest.
		The Battering Ram can also unfreeze frozen props (if enabled).
		Type /wanted <name> to alert the public to the presence of a criminal.]],
	weapons = { "taser", "arrest_stick", "unarrest_stick", "swb_glock18", "stunstick", "door_ram", "weaponchecker", "radar_gun" },
	command = "cp",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 13.33,
	admin = 0,
	vote = false,
	hasLicense = true,
	ammo = {
		["pistol"] = 60,
	}
})

TEAM_GANG = DarkRP.createJob("Gangster", {
	color = Color(75, 75, 75, 255),
	model = {
		"models/player/Group03/Female_01.mdl",
		"models/player/Group03/Female_02.mdl",
		"models/player/Group03/Female_03.mdl",
		"models/player/Group03/Female_04.mdl",
		"models/player/Group03/Female_06.mdl",
		"models/player/group03/male_01.mdl",
		"models/player/Group03/Male_02.mdl",
		"models/player/Group03/male_03.mdl",
		"models/player/Group03/Male_04.mdl",
		"models/player/Group03/Male_05.mdl",
		"models/player/Group03/Male_06.mdl",
		"models/player/Group03/Male_07.mdl",
		"models/player/Group03/Male_08.mdl",
		"models/player/Group03/Male_09.mdl"},
	description = [[The lowest person of crime.
		A gangster generally works for the Mobboss who runs the crime family.
		The Mob boss sets your agenda and you follow it or you might be punished.]],
	weapons = { "carjacker" },
	command = "gangster",
	max = 5,
	salary = GAMEMODE.Config.normalsalary * 4,
	admin = 0,
	vote = false,
	hasLicense = false
})

TEAM_MOB = DarkRP.createJob("Mob Boss", {
	color = Color(25, 25, 25, 255),
	model = "models/player/gman_high.mdl",
	description = [[The Mob boss is the boss of the criminals in the city.
		With his power he coordinates the gangsters and forms an efficient crime organization.
		He has the ability to break into houses by using a lockpick.
		The Mob boss posesses the ability to unarrest you.]],
	weapons = {"lockpick", "unarrest_stick", "chopshop_tool" },
	command = "mobboss",
	max = 1,
	salary = GAMEMODE.Config.normalsalary * 5,
	admin = 0,
	vote = false,
	hasLicense = false,
	NeedToChangeFrom = TEAM_GANG,
})

TEAM_GUN = DarkRP.createJob("Gun Dealer", {
	color = Color(255, 140, 0, 255),
	model = "models/player/monk.mdl",
	description = [[A Gun Dealer is the only person who can sell guns to other people.
		Make sure you aren't caught selling illegal firearms to the public! You might get arrested!]],
	weapons = {},
	command = "gundealer",
	max = 3,
	salary = GAMEMODE.Config.normalsalary * 3,
	admin = 0,
	vote = false,
	hasLicense = false
})

TEAM_PARAMEDIC = DarkRP.createJob("Paramedic", {
	color = Color(47, 79, 79, 255),
	model = "models/player/hostage/hostage_01.mdl",
	description = [[With your medical knowledge you work to restore players to full health.
		Without a medic, people cannot be healed.
		Left click with the Medical Kit to heal other players.
		Right click with the Medical Kit to heal yourself.
		You also have access to a defibrillator.
		You may access the Ambulances in the Nexus garage as well.]],
	weapons = { "med_kit", "defibrillator" },
	command = "paramedic",
	max = 5,
	salary = GAMEMODE.Config.normalsalary * 4,
	admin = 0,
	vote = false,
	hasLicense = false,
	medic = true
})

TEAM_SWAT = DarkRP.createJob("S.W.A.T", {
	color = Color(49, 74, 94, 255),
	model = "models/player/swat.mdl",
	description = [[The elite of the police force.
		Your job is to run in when everyone else is running out. You spawn with a rifle.
		Abuse it and be banned.]],
	weapons = { "taser", "arrest_stick", "unarrest_stick", "swb_deagle", "swb_ak47", "stunstick", "door_ram", "weaponchecker", "riot_shield" },
	command = "swat",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 13.33,
	admin = 0,
	vote = true,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_SECRETSERVICE = DarkRP.createJob("Secret Service", {
	color = Color(23, 25, 60, 255),
	model = "models/player/riot.mdl",
	description = [[Your job is to protect the Mayor.
		That's all you do.
		You should never leave the Mayor's side.
		Players are allowed to randomly kill/demote you.
		If the Mayor dies, you will lose your job.]],
	weapons = { "taser", "arrest_stick", "unarrest_stick", "swb_deagle", "swb_aug", "stunstick", "door_ram", "weaponchecker" },
	command = "secretservice",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 13.33,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
	customCheck = function( ply ) return ( team.NumPlayers( TEAM_MAYOR ) > 0 and ply:Team( ) ~= TEAM_MAYOR ) end,
	customCheckFailMsg = "There must be a Mayor to become Secret Service, and you can't be the Mayor!",
	PlayerDeath = function( ply, weapon, killer ) ply:changeTeam( TEAM_CITIZEN, true ) end
})

TEAM_CHIEF = DarkRP.createJob("Civil Protection Chief", {
	color = Color(20, 20, 255, 255),
	model = "models/player/barney.mdl",
	description = [[The Chief is the leader of the Civil Protection unit.
		Coordinate the police force to enforce law in the city.
		Hit a player with arrest baton to put them in jail.
		Bash a player with a stunstick and they may learn to obey the law.
		The Battering Ram can break down the door of a criminal, with a warrant for his/her arrest.
		Type /wanted <name> to alert the public to the presence of a criminal.]],
	weapons = { "taser", "arrest_stick", "unarrest_stick", "swb_deagle", "stunstick", "door_ram", "weaponchecker", "radar_gun" },
	command = "chief",
	max = 1,
	salary = GAMEMODE.Config.normalsalary * 13.33,
	admin = 0,
	vote = false,
	hasLicense = true,
	chief = true,
	NeedToChangeFrom = { TEAM_POLICE, TEAM_SWAT },
	ammo = {
		["pistol"] = 60,
	}
})

TEAM_MAYOR = DarkRP.createJob("Mayor", {
	color = Color(150, 20, 20, 255),
	model = "models/player/breen.mdl",
	description = [[The Mayor of the city creates laws to govern the city.
		If you are the mayor you may create and accept warrants.
		Type /wanted <name>  to warrant a player.
		Type /jailpos to set the Jail Position.
		Type /lockdown initiate a lockdown of the city.
		Everyone must be inside during a lockdown.
		The cops patrol the area.
		/unlockdown to end a lockdown]],
	weapons = { "unarrest_stick" },
	command = "mayor",
	max = 1,
	salary = GAMEMODE.Config.normalsalary * 14,
	admin = 0,
	vote = true,
	hasLicense = false,
	mayor = true,
	PlayerDeath = function( ply, weapon, killer )
		if ( IsValid( killer ) and killer:IsPlayer( ) and killer:isCP( ) ) then
			killer:changeTeam( TEAM_CITIZEN, true );
			killer:SetWanted( 300, "is wanted for killing the Mayor as Civil Protection." );
		else
			ply:changeTeam( TEAM_CITIZEN, true ) 
			SHNOOB_VARS:Set( "MayorLaws", SVNOOB_VARS:Get( "DefaultMayorLaws", true ) )
		end
	end
})

TEAM_HOBO = DarkRP.createJob("Hobo", {
	color = Color(80, 45, 0, 255),
	model = "models/player/corpse1.mdl",
	description = [[The lowest member of society. Everybody laughs at you.
		You have no home.
		Beg for your food and money.
		Sing for everyone who passes to get money.
		Make your own wooden home somewhere in a corner or outside someone else's door.
		YOU CAN BE ARRESTED ON SIGHT WITHOUT WARNING.
		The reason for this is because of a deadly disease a Hobo can carry, causing them to turn into a zombie within minutes.]],
	weapons = {},
	command = "hobo",
	max = 5,
	salary = 0,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = false,
	hobo = true,
	PlayerDeath = function( ply, weapon, killer ) ply:changeTeam( TEAM_CITIZEN, true ) end
})

TEAM_ZOMBIE = DarkRP.createJob("Zombie", {
	color = Color(172, 94, 64, 255),
	model = "models/player/zombie_classic.mdl",
	description = [[You are a zombie.
		You may at one point been a hobo.
		Find brains. Eat them.
		By the way, everyone wants to kill you.
		Here's a crowbar, have fun.
		The zombie cannot use guns, but is the only class allow to RDM with limitations.]],
	weapons = {"weapon_crowbar"},
	command = "zombie",
	max = 100,
	salary = 0,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = false,
	hobo = true,
	customCheck = function( ply ) return ply:getDarkRPVar( "CanZombie" ) end,
	customCheckFailMsg = "You can't just turn into a zombie!",
	PlayerDeath = function( ply, weapon, killer ) ply:changeTeam( TEAM_CITIZEN, true ) ply.overrideJobWaitTime = true end
})

TEAM_SPY = DarkRP.createJob("Spy", {
	color = Color( 167, 84, 134, 255),
	model = "models/player/arctic.mdl",
	description = [[You are a spy.
		You work for whoever you choose.
		You can disguise yourself, and sell different types of spy kits.
		If you die, you revert back to a citizen.]],
	weapons = { "swb_fiveseven", "spy_kit", "lockpick" },
	command = "spy",
	max = 3,
	salary = GAMEMODE.Config.normalsalary * 4,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
	PlayerDeath = function( ply, weapon, killer ) ply:changeTeam( TEAM_CITIZEN, true ) end,
})

TEAM_GUARD = DarkRP.createJob("Security Guard", {
	color = Color(203, 140, 216, 255),
	model = "models/player/combine_soldier_prisonguard.mdl",
	description = [[You wanted to be a cop.
		They weren't hiring.
		Go guard the mall or something.]],
	weapons = {"stunstick"},
	command = "guard",
	max = 5,
	salary = GAMEMODE.Config.normalsalary * 3,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
})

TEAM_CARDEALER = DarkRP.createJob("Car Dealer", {
	color = Color(235, 232, 107, 255),
	model = "models/player/alyx.mdl",
	description = [[You are a car dealer.
		Sell cars.]],
	weapons = {},
	command = "cardealer",
	max = 5,
	salary = GAMEMODE.Config.normalsalary * 3,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_BUSDRIVER = DarkRP.createJob("Bus Driver", {
	color = Color(169, 166, 76, 255),
	model = "models/player/eli.mdl",
	description = [[Hopefully you speak gewd Engrish.
		Buses should be running regular routes.
		Just drive around and stop for people.
		You should charge people when they get on the bus. Buses have a flat rate, so set it and charge them before you start moving.
		NOTE: Buses disappear and respawn if not used by a Bus Driver for 5 minutes.]],
	weapons = {},
	command = "busdriver",
	max = 1,
	salary = GAMEMODE.Config.normalsalary * 3,
	admin = 0,
	vote = true,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_HITMAN = DarkRP.createJob("Hitman", {
	color = Color(128, 21, 21, 255),
	model = "models/player/phoenix.mdl",
	description = [[You may accept hits from people.
		They're only able to give you one if they have revenge on the player. 
		You may not make up your own hits.]],
	weapons = { "unarrest_stick", "swb_deagle", "swb_awp", "swb_knife", "med_kit", "spy_kit", "lockpick", "defibrillator" },
	command = "hitman",
	max = 2,
	salary = GAMEMODE.Config.normalsalary * 4,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
	PlayerDeath = function( ply, weapon, killer ) ply:changeTeam( TEAM_CITIZEN, true ) end
})

TEAM_MECHANIC = DarkRP.createJob("Mechanic", {
	color = Color(65, 162, 97, 255),
	model = "models/player/guerilla.mdl",
	description = [[The mechanic can fix vehicles and props.
		Mechanics are only class that can buy gas cans.]],
	weapons = { "repair_tool" },
	command = "mechanic",
	max = 5,
	salary = GAMEMODE.Config.normalsalary * 3,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_SALVAGER = DarkRP.createJob("Salvager", {
	color = Color(82, 199, 109, 255),
	model = "models/player/soldier_stripped.mdl",
	description = [[The salvager runs chop shops.
		They can work alone or in teams to strip cars.
		They don't have to be criminals!
		Salvagers can buy cars back from honest citizens who just don't need them anymore.]],
	weapons = { "chopshop_tool" },
	command = "salvager",
	max = 8,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_FOREMAN = DarkRP.createJob("Mining Foreman", {
	color = Color(119, 138, 54, 255),
	model = "models/player/group01/female_03.mdl",
	description = [[The Mining Foreman can spawn the Drill.
		You cannot be demoted while your drill is spawned, but you will need a team of people to defend it.
		Do your job or you will be demoted!]],
	weapons = { "shovel" },
	command = "foreman",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_SCIENTIST = DarkRP.createJob("Scientist", {
	color = Color(205, 135, 77, 255),
	model = "models/player/kleiner.mdl",
	description = [[Locked in a quiet room, your job is to study the world.
		YOU CANNOT USE GUNS. 
		You can spawn a Laboratory.
		After a small amount of research, you can create a Plague Canister.]],
	weapons = { "disorientator" },
	command = "scientist",
	max = 2,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_CRAB = DarkRP.createJob("Crab Person", {
	color = Color(176, 202, 101, 255),
	model = "models/player/headcrab.mdl",
	description = [[Go forth and multiply!
		The oldest Crab becomes the Crab Queen when fully grown.
		Crab Hills will occasionally spawn gems if near the Queen.
		CRABS HAVE NO RIGHTS! THEY CAN BE KILLED ON SIGHT!]],
	weapons = { "crab_bite" },
	command = "crab",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
	modelScale = 0.1,
	PlayerDeath = function( ply, weapon, killer ) ply:changeTeam( TEAM_CITIZEN, true ) end
})

TEAM_CONSTRUCTION = DarkRP.createJob("Construction Worker", {
	color = Color( 230, 126, 34, 255),
	model = "models/player/Group01/Male_04.mdl",
	description = [[You build things for other people, or yourself. 
		You have a higher prop limit.
		You are a peaceful person and enjoy building structures for others to enjoy. 
		You cannot be raided. You have nothing of interest to steal.
		As such, you cannot have any illegal money printers.]],
	weapons = {},
	command = "constructionworker",
	max = 3,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_THIEF = DarkRP.createJob("Thief", {
	color = Color(122, 162, 157, 255),
	model = "models/player/odessa.mdl",
	description = [[You are a thief.
		Feel free to steal things.]],
	weapons = { "lockpick", "swb_knife" },
	command = "thief",
	max = 5,
	salary = GAMEMODE.Config.normalsalary * 3,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_HACKER = DarkRP.createJob("Hacker", {
	color = Color(136, 122, 149, 255),
	model = "models/player/Group01/Male_07.mdl",
	description = [[You get a keypad cracker.
		Be thankful we gave you anything at all!]],
	weapons = {"keypad_cracker"},
	command = "hacker",
	max = 3,
	salary = GAMEMODE.Config.normalsalary * 3,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_BMARKET = DarkRP.createJob("Black Market Dealer", {
	color = Color(87, 203, 182, 255),
	model = "models/player/leet.mdl",
	description = [[You have access to illegal weapons, lockpicks, and keypad crackers, but you have to buy them.
		Or sell them.
		And grenades.
		Did I mention grenades?]],
	weapons = {},
	command = "blackmarket",
	max = 3,
	salary = GAMEMODE.Config.normalsalary * 3,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_HERBALIST = DarkRP.createJob("Herbalist", {
	color = Color( 41, 128, 185, 255),
	model = "models/player/Group01/Male_05.mdl",
	description = [[You're very skilled in gathering herbs.
		You're able to uproot them quickly and intact.
		You cannot use weapons, and you may be demoted for being away.
		You can also sell Potion Launchers.]],
	weapons = {},
	command = "herbalist",
	max = 3,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
	--PlayerDeath = function( ply, weapon, killer ) ply:changeTeam( TEAM_CITIZEN, true ) end
})

TEAM_SPECIALIST = DarkRP.createJob("Specialist", {
	color = Color(69, 157, 168, 255),
	model = "models/player/group03/male_05.mdl",
	description = [[Like a ghost in the night, you slip in, you take what you want.
		You're a wild and crazy guy!]],
	weapons = {"vip_lockpick", "swb_tmp", "swb_p228", "spy_kit" },
	command = "specialist",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 11,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
	customCheck = function( ply ) return ply:IsVIP( ) end,
	customCheckFailMsg = "You must be VIP to select that job!"
})

TEAM_MERCENARY = DarkRP.createJob("Mercenary", {
	color = Color(68, 136, 123, 255),
	model = "models/player/combine_super_soldier.mdl",
	description = [[You can do pretty much whatever you want,
		as long as you're getting paid to do it.
		You are NOT a hitman, but you can be hired to help during robberies, battles, etc (just not for individual hits).]],
	weapons = {"vip_lockpick", "swb_tmp"},
	command = "mercenary",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 11,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
	customCheck = function( ply ) return ply:IsVIP( ) end,
	customCheckFailMsg = "You must be VIP to select that job!"
})

TEAM_UNDERCOVER = DarkRP.createJob("Special Agent", {
	color = Color(50, 56, 71, 255),
	model = "models/player/combine_soldier.mdl",
	description = [[Responsible for infiltrating criminals organizations, Special Agents are responsible for most major busts.
		Be careful not to blow your cover!
		Agents receive some specialized tools to carry out their missions.]],
	weapons = { "taser", "spy_kit", "arrest_stick", "unarrest_stick", "swb_deagle", "stunstick", "door_ram", "weaponchecker", "swb_aug", "radar_gun" },
	command = "agent",
	max = 0,
	salary = GAMEMODE.Config.normalsalary * 13.33,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false,
	customCheck = function( ply ) return ply:IsVIP( ) end,
	customCheckFailMsg = "You must be VIP to select that job!"
})

TEAM_CAMERAMAN = DarkRP.createJob("Camera Man", {
	color = Color(72, 198, 214, 255),
	model = "models/player/hostage/hostage_03.mdl",
	description = [[You are the camera guy.
		You decide what gets seen on all of the TVs in Evocity.  Make us proud!
		Use /news <msg> to broadcast news updates to go along with the video feed.
		Oh btw, cameramen don't carry guns!]],
	weapons = { "news_camera" },
	command = "cameraman",
	max = 1,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = true,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_TIDES = DarkRP.createJob("Tides Manager", {
	color = Color(234, 74, 119, 255),
	model = "models/player/group01/female_05.mdl",
	description = [[You are the official and sole manager of the Tides Centre.
		This means you're the only one who can control the theater playback screen.
		Play videos people like or risk getting demoted.]],
	weapons = {},
	command = "tides",
	max = 1,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = true,
	hasLicense = false,
	candemote = true,
	hobo = false
})

TEAM_BARTENDER = DarkRP.createJob("Bartender", {
	color = Color(171, 56, 95, 255),
	model = "models/player/hostage/hostage_04.mdl",
	description = [[Your friendly neighborhood bartender.
		Why is booze legal when drugs aren't?
		These are the mysteries we are faced with.
		The Mayor *can* outlaw alchohol, so be careful!]],
	weapons = {},
	command = "bartender",
	max = 1,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = true,
	hasLicense = false,
	candemote = true,
	hobo = false
})

/*TEAM_PHOTOGRAPHER = DarkRP.createJob("Photographer", {
	color = Color( 155, 89, 182, 255 ),
	model = "models/player/magnusson.mdl",
	description = [[You have the ability to take pictures in-game and display them on your picture frames with the special camera you have.
		Press 'E' on a picture frame to change the image. People may want to buy picture frames off you.]],
	weapons = { "noob_camera" },
	command = "photographer",
	max = 1,
	salary = GAMEMODE.Config.normalsalary * 2,
	admin = 0,
	vote = false,
	hasLicense = false,
	candemote = true,
	hobo = false
})*/

-- Compatibility for when default teams are disabled
TEAM_CITIZEN = TEAM_CITIZEN  or -1
TEAM_POLICE  = TEAM_POLICE   or -1
TEAM_GANG    = TEAM_GANG     or -1
TEAM_MOB     = TEAM_MOB      or -1
TEAM_GUN     = TEAM_GUN      or -1
TEAM_MEDIC   = TEAM_MEDIC    or -1
TEAM_CHIEF   = TEAM_CHIEF    or -1
TEAM_MAYOR   = TEAM_MAYOR    or -1
TEAM_HOBO    = TEAM_HOBO     or -1

/*
--------------------------------------------------------
HOW TO MAKE A DOOR GROUP
--------------------------------------------------------
AddDoorGroup("NAME OF THE GROUP HERE, you see this when looking at a door", Team1, Team2, team3, team4, etc.)


The default door groups, can also be used as examples:
*/
AddDoorGroup("Government Owned", TEAM_CHIEF, TEAM_POLICE, TEAM_SWAT, TEAM_SECRETSERVICE, TEAM_UNDERCOVER, TEAM_MAYOR )
AddDoorGroup("Gundealer only", TEAM_GUN)
AddDoorGroup("Public Transportation", TEAM_BUSDRIVER )
AddDoorGroup("Unownable", nil )
AddDoorGroup("Medical Personnel", TEAM_PARAMEDIC )

/*
--------------------------------------------------------
HOW TO MAKE AN AGENDA
--------------------------------------------------------
AddAgenda(Title of the agenda, Manager (who edits it), Listeners (the ones who just see and follow the agenda))

The default agenda's, can also be used as examples:
*/
AddAgenda("Gangster's agenda", TEAM_MOB, {TEAM_GANG})
AddAgenda("Police agenda", TEAM_MAYOR, { TEAM_CHIEF, TEAM_POLICE, TEAM_SWAT, TEAM_SECRETSERVICE, TEAM_UNDERCOVER } )


/*
---------------------------------------------------------------------------
HOW TO MAKE A GROUP CHAT
---------------------------------------------------------------------------
Pick one!
GAMEMODE:AddGroupChat(List of team variables separated by comma)

or

GAMEMODE:AddGroupChat(a function with ply as argument that returns whether a random player is in one chat group)
This one is for people who know how to script Lua.

*/
GAMEMODE:AddGroupChat(function(ply) return ply:isCP() end)
GAMEMODE:AddGroupChat(TEAM_MOB, TEAM_GANG)

/*---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------*/
GAMEMODE.DefaultTeam = TEAM_CITIZEN

/*---------------------------------------------------------------------------
Define which teams belong to civil protection
Civil protection can set warrants, make people wanted and do some other police related things
---------------------------------------------------------------------------*/
GAMEMODE.CivilProtection = {
	[TEAM_POLICE] = true,
	[TEAM_SWAT] = true,
	[TEAM_SECRETSERVICE] = true,
	[TEAM_UNDERCOVER] = true,
	[TEAM_CHIEF] = true,
	[TEAM_MAYOR] = true,
}

/*---------------------------------------------------------------------------
Enable hitman goodies on this team
---------------------------------------------------------------------------*/
DarkRP.addHitmanTeam(TEAM_HITMAN)

/*---------------------------------------------------------------------------
Default demote groups
---------------------------------------------------------------------------*/
DarkRP.createDemoteGroup("Cops", {TEAM_POLICE, TEAM_CHIEF})
DarkRP.createDemoteGroup("Gangsters", {TEAM_GANG, TEAM_MOB})
