ENUM_HAT_BONE = 1
ENUM_HAT_ATTACHMENT = 2
ENUM_CAM_BEGINTRANSFER = 3
ENUM_CAM_SENDPART = 4
ENUM_PICFRAME_OPENMENU = 5
ENUM_PICFRAME_SETFILE = 6
ENUM_PICFRAME_UPDATEIMG = 7
ENUM_PICFRAME_DELETE = 8
ENUM_INJURIES_LEGS = 9
ENUM_INJURIES_ARMS = 10
ENUM_REVENGE_SENDREVENGE = 11
ENUM_REVENGE_REMOVEREVENGE = 12
ENUM_REVENGE_INCREMENTREVENGE = 13
ENUM_TEMPWEPS_ADDWEP = 14
ENUM_TEMPWEPS_REMOVEWEP = 15
ENUM_TEMPWEPS_CLEARWEPS = 16
ENUM_BANKITEMS_ADDITEM = 17
ENUM_BANKITEMS_REMOVEITEM = 18
ENUM_CLANMENU_BEGINSENDING = 19
ENUM_CLANMENU_ADDMEMBER = 20
ENUM_CLANMENU_ENDSENDING = 21
ENUM_WEAPONRENTAL_ALREADYHAS = 22
ENUM_WEAPONRENTAL_CANTAFFORD = 23
ENUM_WEAPONRENTAL_RENTSUCCESS = 24
ENUM_WEAPONRENTAL_DOESNTHAVE = 25
ENUM_WEAPONRENTAL_CANCELSUCCESS = 26
ENUM_WEAPONRENTAL_ALREADYHASPERMA = 27
ENUM_MISC_NET_PARTICLES = 28

NOOBRP = NOOBRP or { }
NOOBRP.Titles = NOOBRP.Titles or { }
ENUM_TITLES_BEGINSEND = 28
ENUM_TITLES_SENDTITLE = 29
ENUM_TITLES_ENDSEND = 30
ENUM_TITLES_GARDENER = 31
NOOBRP.Titles[ENUM_TITLES_GARDENER] = { col = Color( 45, 175, 45 ), title = "Gardener" }
ENUM_TITLES_AVENGER = 32
NOOBRP.Titles[ENUM_TITLES_AVENGER] = { col = Color( 175, 45, 45 ), title = "Avenger" }
ENUM_TITLES_ALCHEMIST = 33
NOOBRP.Titles[ENUM_TITLES_ALCHEMIST] = { col = Color( 45, 45, 175 ), title = "Alchemist" }

COLOR_RED = Color( 210, 77, 87 )
COLOR_PINK =  Color( 244, 130, 131 )
COLOR_PURPLE = Color( 155, 89, 182 )
COLOR_BLUE = Color( 92, 151, 191 )
COLOR_GREEN = Color( 102, 204, 153 )
COLOR_YELLOW = Color( 245, 215, 110 )
COLOR_ORANGE = Color( 230, 126, 34 )
COLOR_GRAY = Color( 171, 183, 183 )
COLOR_WHITE = Color( 255, 255, 255 )
COLOR_BLACK = Color( 0, 0, 0 )